# Generated by Django 5.2.8 on 2025-11-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_democlass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoClass',
            new_name='DemoModel',
        ),
    ]
