# Generated by Django 5.2.8 on 2025-11-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_rename_democlass_demomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='field1',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(max_length=32),
        ),
    ]
